name: CI/CD Pipeline - Development

on:
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set environment variables
        env:
          API_KEY: ${{ secrets.HARVARD_API_KEY }}
        run: echo "api.key=${API_KEY}" >> $GITHUB_ENV

      - name: Run Unit Tests
        run: mvn test

      - name: Check Test Coverage
        run: mvn verify
